import uuid
from time import sleep

from colorama import Fore

print("")
print(Fore.RED + " " + " Loading update code MoringStar....")
sleep(1.0)
print("server   Error")
print("server   On")
print("server   Error")
print("server   On")
print("server   Error")
print("server   Error")
print("server   Error")
print("server   Error")
print("server   On")
print("server   Error")
print("server   On")
print("server   Error")
print("server   Error")
print("server   On")
print("server   On")
print("server   On")
print("server   On")
loo = """
 server Open On Ok """
for i in loo:
    sleep(0.02)
    print(i, end='', flush=True)
print()
sleep(0.9)
print(Fore.GREEN + "  " + "{" + "_" * 40 + "}")
print("   " + Fore.RED + 'Code Fil Gp Splus.ir>> ', "web/splus.ir", uuid.uuid1())
print()
print("   " + Fore.RED + 'Cod Fil  Gp Splus.ir>> ', 'web/splus.ir', uuid.uuid4())
print(Fore.GREEN + "  " + "(" + "_" * 40 + ")")
print()
print("God_Filtering_Hacking")
print(Fore.YELLOW+"Lucifer_Moring_Star===Amir_hack")
print("Amir_Wolf++Amir_hack")
print("Amir_torento++Amir_hack")
print("Mahdiyar,Amir_Megateron++Amir_hack")
print("A+A+A=A3")
print("Moring_Star_Filtering_hacking")
input()
